version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/base:2026.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Get pwd
          command: pwd
      - run:
          name: "Docker compose"
          command: docker compose up -d
      - run:
          name: "Test data-collector"
          command: docker compose exec data-collector uv run python -m pytest -s -vv

workflows:
  ci:
    jobs:
      - build-and-test