version: 2.1
jobs:
  database-migration:
    docker:
      - image: cimg/base:2026.03
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          working_directory: ~/projects/services/flyway
          name: "Build flyway container"
          command: docker build -f Dockerfile -t flyway:run-migration-scripts .
      - run:
          name: "Execute migration"
          command: docker run flyway:run-migration-scripts -url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME} -schema=public -user=${DB_USER} -password=${DB_PASSWORD} migrate

workflows:
  db-migration:
    jobs:
      - database-migration